/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    kotlin("jvm") version "1.3.70"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("com.typesafe.akka:akka-actor_2.13:2.6.3")
}

application {
    // Define the main class for the application.
    mainClassName = "org.elu.kotlin.akka.SupervisionKt"
}
