/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.elu.kotlin.akka

import akka.actor.ActorRef
import akka.actor.ActorSystem
import akka.actor.PoisonPill
import akka.actor.Props

fun main() {
  val system = ActorSystem.create("actor-paths")

  val counter1 = system.actorOf(Props.create(Counter::class.java), "Counter")
  println("Actor reference for counter1: $counter1")

  val counterSelection1 = system.actorSelection("counter")
  println("Actor selection for counterSelection1: $counterSelection1")

  counter1.tell(PoisonPill.getInstance(), ActorRef.noSender())
  Thread.sleep(100)

  val counter2 = system.actorOf(Props.create(Counter::class.java), "counter")
  println("Actor reference for counter2: $counter2")

  val counterSelection2 = system.actorSelection("counter")
  println("Actor selection for counterSelection2: $counterSelection2")

  Thread.sleep(1000)
  system.terminate()
}
