/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.elu.kotlin.akka

import akka.actor.AbstractActor
import akka.actor.ActorSystem
import akka.actor.Props
import akka.japi.pf.ReceiveBuilder

data class WhoToGreet(val who: String)

class Greeter : AbstractActor() {
    override fun createReceive(): Receive =
        ReceiveBuilder().match(WhoToGreet::class.java) {
            println("Hello ${it.who}")
        }.build()
}

fun main() {
    val system = ActorSystem.create("Hello-Akka")

    val greeter = system.actorOf(Props.create(Greeter::class.java), "greeter")

    greeter.tell(WhoToGreet("Akka"), greeter)
}
