/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.elu.kotlin.akka

import akka.actor.ActorRef
import akka.actor.ActorSystem
import akka.actor.Props

fun main() {
    val system = ActorSystem.create("hotswap-become")

    val userStorage = system.actorOf(Props.create(UserStorage::class.java), "userStorage")

    userStorage.tell(Operation(Create, User("Admin", "admin@test.com")), ActorRef.noSender())
    userStorage.tell(Connect, ActorRef.noSender())
    userStorage.tell(Disconnect, ActorRef.noSender())

    Thread.sleep(100)
    system.terminate()
}
