/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.elu.kotlin.akka

import akka.actor.ActorRef
import akka.actor.ActorSystem
import akka.actor.Props

fun main() {
  val system = ActorSystem.create("persistent-actors")

  val counter = system.actorOf(Props.create(Counter::class.java))

  counter.tell(Cmd(Increment(3)), ActorRef.noSender())
  counter.tell(Cmd(Increment(5)), ActorRef.noSender())
  counter.tell(Cmd(Decrement(3)), ActorRef.noSender())
  counter.tell("print", ActorRef.noSender())

  Thread.sleep(3000)
  system.terminate()
}
